export const ROUTES = {
  LOGIN: "/login",
  VERIFY_OTP: "/verify-otp",
  HOME: "/",
  CATEGORIES: "/categories",
  JOBS: "/jobs",
  SUBADMIN_MANAGEMENT: "/administrators",
  UNAUTHORIZED: "/unauthorized",
  AUTHENTICATION: "/authentication",
  SUBSCRIPTIONS: "/subscriptions",
  ALBUM: "/album",
  ALBUMDETAILS: "/album/details",
  PRODUCTS: "/products",
  PRODUCTDETAILS: "/products/details",
  CREDITS: "/credits",
  DASHBOARD: "/dashboard",
  JOB_CATEGORIES: "/job-categories",
  CITY_MANAGEMENT: "/city-management",
  USERS: "/users",
  NOTIFIICATIONS: "/notifications",
  COMPANIES: "/companies",
  COURSES: "/courses",
  ADVERTISEMENT: "/advertisements",
  ADD_NEW_ADS : "/advertisements/add",
  COURSE_DETAILS: "/courses/details",
  LESSION_DETAILS: "/courses/videos",
  SPIN_WHEEL: "/spin-wheel",
  PAYMENTS: "/payments",
  JOB_APPLICATIONS: "/jobs/applications",
  PROFILE: "/profile",
  APPLICATIONS: "/applications",
  ORGANIZATIONS: "/organizations",
  ORGANIZATION_DETAILS: "/organizations/details"
};
